# Generated by Django 2.2.1 on 2019-12-29 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createprofile',
            name='email',
        ),
    ]
