# Generated by Django 2.2.1 on 2019-12-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_createprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='createprofile',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
