# Generated by Django 2.0 on 2019-05-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190515_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createprofile',
            name='category',
        ),
    ]
