# Generated by Django 2.2.1 on 2019-12-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.FileField(blank=True, null=True, upload_to='')),
                ('image2', models.FileField(blank=True, null=True, upload_to='')),
                ('image3', models.FileField(blank=True, null=True, upload_to='')),
                ('image4', models.FileField(blank=True, null=True, upload_to='')),
                ('image5', models.FileField(blank=True, null=True, upload_to='')),
                ('image6', models.FileField(blank=True, null=True, upload_to='')),
                ('image7', models.FileField(blank=True, null=True, upload_to='')),
                ('image8', models.FileField(blank=True, null=True, upload_to='')),
                ('username', models.TextField(blank=True, null=True)),
                ('details', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='postimages')),
            ],
        ),
    ]
