# Generated by Django 2.2.1 on 2019-12-29 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image8',
        ),
    ]
