# Generated by Django 2.2.1 on 2019-12-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_post_image8'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image8',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
